                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 9999 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 8888 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 8888 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 7777 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 7777 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 6666 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 6666 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 5555 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 5555 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 4444 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 4444 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 3333 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 3333 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 2222 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 2222 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 1111 -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport 1111 -j ACCEPT
